name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
            TAG=` echo ${{github.sha}} | cut -c1-6`
            echo "$TAG"
            docker build -t 1111darsh/backend-go:$TAG -t 1111darsh/backend-go:latest .
            docker push 1111darsh/backend-go:$TAG
            docker push 1111darsh/backend-go:latest